# Add your OpenAI API key here for deployment
# OPENAI_API_KEY = "your-api-key-here"

# Note: For cloud deployment (Streamlit Cloud, Heroku, etc.),
# set this as an environment variable in your deployment platform