# Nixpacks configuration for Railway
[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "rustc", "cargo", "pkg-config"]
aptPkgs = ["python3-pip", "python3-dev", "build-essential"]

[phases.install]
cmds = [
    "python --version",
    "python -m ensurepip --upgrade",
    "python -m pip install --upgrade pip setuptools wheel",
    "python -m pip install -r requirements.txt"
]

[start]
cmd = "python -m streamlit run app_main.py --server.port $PORT --server.address 0.0.0.0"