[phases.setup]
nixPkgs = ["...", "gcc", "rustc", "cargo"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "streamlit run app_main.py --server.port $PORT --server.address 0.0.0.0"