[phases.setup]
nixPkgs = ["python311", "gcc", "rustc", "cargo"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "python -m streamlit run app_main.py --server.port $PORT --server.address 0.0.0.0"